project:
  type: website
  output-dir: docs

website:
  title: "Bora's Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/akifboraeren
      - icon: instagram
        href: https://www.instagram.com/akfbora/
      - icon: linkedin
        href: https://linkedin.com
      - icon: steam
        href: https://steamcommunity.com/profiles/76561198152536340/

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    font: Comicsans 
    theme: 
      light: sandstone 
      dark: superhero
    css: styles.css


editor: visual

